const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('savvy', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (settings) => ipcRenderer.invoke('set-settings', settings),
  oracleApi: (url, user, pass) => ipcRenderer.invoke('oracle-api', { url, user, pass }),
  captureScreen: () => ipcRenderer.invoke('capture-screen'),
  getCursorContext: () => ipcRenderer.invoke('get-cursor-context'),
  getWindowSources: () => ipcRenderer.invoke('get-window-sources'),
  captureWindow: (windowId) => ipcRenderer.invoke('capture-window', windowId),
  closeOverlay: () => ipcRenderer.send('close-overlay'),
  setOverlaySize: (size) => ipcRenderer.invoke('set-overlay-size', size),
  getOverlayPosition: () => ipcRenderer.invoke('get-overlay-position'),
  setOverlayPosition: (pos) => ipcRenderer.invoke('set-overlay-position', pos),
  centerIfNeeded: (x, y) => ipcRenderer.invoke('center-if-needed', { x, y }),
  centerWindow: () => ipcRenderer.invoke('center-window'),
  clearBubbleMode: () => ipcRenderer.invoke('clear-bubble-mode'),
  moveOverlayToCorner: () => ipcRenderer.invoke('move-overlay-to-corner'),
  loadKnowledgeBase: () => ipcRenderer.invoke('load-knowledge-base'),
  loginWithSso: (backendUrl, tenantId) => ipcRenderer.invoke('login-with-sso', { backendUrl, tenantId }),
  getAuthState: () => ipcRenderer.invoke('get-auth-state'),
  logout: () => ipcRenderer.invoke('logout'),
  getUiState: (key) => ipcRenderer.invoke('get-ui-state', key),
  setUiState: (key, value) => ipcRenderer.invoke('set-ui-state', key, value),
  getConversationHistory: () => ipcRenderer.invoke('get-conversation-history'),
  saveConversationHistory: (history) => ipcRenderer.invoke('set-conversation-history', history),

  // Desktop app bridges
  getLocalToken: () => ipcRenderer.invoke('auth:getLocalToken'),
  windowMinimize: () => ipcRenderer.send('window:minimize'),
  windowMaximize: () => ipcRenderer.send('window:maximize'),
  windowClose: () => ipcRenderer.send('window:close'),
  openFiles: (options) => ipcRenderer.invoke('dialog:openFiles', options),
  saveFile: (options) => ipcRenderer.invoke('dialog:saveFile', options),
  showMessageBox: (options) => ipcRenderer.invoke('dialog:showMessageBox', options),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  writeFile: (filePath, data) => ipcRenderer.invoke('file:write', filePath, data),
  openExternal: (url) => ipcRenderer.send('shell:openExternal', url),
  apiRequest: (opts) => ipcRenderer.invoke('api:request', opts),
  storeGet: (key) => ipcRenderer.invoke('store:get', key),
  storeSet: (key, value) => ipcRenderer.invoke('store:set', key, value),
});
